services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: ventas_siman_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: rramos
    ports:
      - "5030:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  backend:
    build:
      context: .
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/ventas_siman_db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: rramos
    ports:
      - "8080:8080"

  frontend:
    build:
      context: ./frontend
    depends_on:
      - backend
    ports:
      - "3000:80"

volumes:
  pgdata:
